### PR TITLE
Enable travis cache

### PR DESCRIPTION
**Pull request by Warchant**
Signed-off-by: Bogdan Vaneev <warchantua@gmail.com>

@Naios 

This PR enables `travis cache`, apt, downloaded llvm dir, dep dir

-----

### What was a problem?

Very long build.

### How this PR fixes the problem?

Caching to the rescue.

Note: PR is WIP, because of slow ci...

### CODE REVIEW

**Comment by Naios** [comment]
Great idea! I'm really looking forward to this one since the long CI builds are painful.
What is missing to get it finished?
Let me know if you need any help.

**Comment by Warchant** [comment]
Something wrong with ccache... I will remove it, to land travis cache.

**Comment by Warchant** [comment]
@Naios it finally worked. You can start review.

**Comment by Naios** [comment]
Looks good to me, thanks for your contribution!

**Pull request merged**
